// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: loyalty.proto

package loyalty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID int32 `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
}

func (x *GetPointsRequest) Reset() {
	*x = GetPointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loyalty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsRequest) ProtoMessage() {}

func (x *GetPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loyalty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsRequest.ProtoReflect.Descriptor instead.
func (*GetPointsRequest) Descriptor() ([]byte, []int) {
	return file_loyalty_proto_rawDescGZIP(), []int{0}
}

func (x *GetPointsRequest) GetCustomerID() int32 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

type GetPointsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID int32 `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Points     int32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *GetPointsReply) Reset() {
	*x = GetPointsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loyalty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPointsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsReply) ProtoMessage() {}

func (x *GetPointsReply) ProtoReflect() protoreflect.Message {
	mi := &file_loyalty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsReply.ProtoReflect.Descriptor instead.
func (*GetPointsReply) Descriptor() ([]byte, []int) {
	return file_loyalty_proto_rawDescGZIP(), []int{1}
}

func (x *GetPointsReply) GetCustomerID() int32 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

func (x *GetPointsReply) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type AddPointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID int32 `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Points     int32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *AddPointsRequest) Reset() {
	*x = AddPointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loyalty_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsRequest) ProtoMessage() {}

func (x *AddPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loyalty_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsRequest.ProtoReflect.Descriptor instead.
func (*AddPointsRequest) Descriptor() ([]byte, []int) {
	return file_loyalty_proto_rawDescGZIP(), []int{2}
}

func (x *AddPointsRequest) GetCustomerID() int32 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

func (x *AddPointsRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type AddPointsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPointsReply) Reset() {
	*x = AddPointsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loyalty_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPointsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsReply) ProtoMessage() {}

func (x *AddPointsReply) ProtoReflect() protoreflect.Message {
	mi := &file_loyalty_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsReply.ProtoReflect.Descriptor instead.
func (*AddPointsReply) Descriptor() ([]byte, []int) {
	return file_loyalty_proto_rawDescGZIP(), []int{3}
}

var File_loyalty_proto protoreflect.FileDescriptor

var file_loyalty_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x22, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x22, 0x48, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x99, 0x01, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x4c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x46, 0x6f, 0x72, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74,
	0x79, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x09, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x6c, 0x6f, 0x79,
	0x61, 0x6c, 0x74, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x75, 0x7a, 0x7a, 0x73, 0x75, 0x72, 0x66, 0x72, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x61, 0x74,
	0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x6f, 0x79, 0x61, 0x6c,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_loyalty_proto_rawDescOnce sync.Once
	file_loyalty_proto_rawDescData = file_loyalty_proto_rawDesc
)

func file_loyalty_proto_rawDescGZIP() []byte {
	file_loyalty_proto_rawDescOnce.Do(func() {
		file_loyalty_proto_rawDescData = protoimpl.X.CompressGZIP(file_loyalty_proto_rawDescData)
	})
	return file_loyalty_proto_rawDescData
}

var file_loyalty_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_loyalty_proto_goTypes = []interface{}{
	(*GetPointsRequest)(nil), // 0: loyalty.GetPointsRequest
	(*GetPointsReply)(nil),   // 1: loyalty.GetPointsReply
	(*AddPointsRequest)(nil), // 2: loyalty.AddPointsRequest
	(*AddPointsReply)(nil),   // 3: loyalty.AddPointsReply
}
var file_loyalty_proto_depIdxs = []int32{
	0, // 0: loyalty.Points.GetPointsForCustomer:input_type -> loyalty.GetPointsRequest
	2, // 1: loyalty.Points.AddPoints:input_type -> loyalty.AddPointsRequest
	1, // 2: loyalty.Points.GetPointsForCustomer:output_type -> loyalty.GetPointsReply
	3, // 3: loyalty.Points.AddPoints:output_type -> loyalty.AddPointsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loyalty_proto_init() }
func file_loyalty_proto_init() {
	if File_loyalty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loyalty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loyalty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPointsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loyalty_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loyalty_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPointsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loyalty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loyalty_proto_goTypes,
		DependencyIndexes: file_loyalty_proto_depIdxs,
		MessageInfos:      file_loyalty_proto_msgTypes,
	}.Build()
	File_loyalty_proto = out.File
	file_loyalty_proto_rawDesc = nil
	file_loyalty_proto_goTypes = nil
	file_loyalty_proto_depIdxs = nil
}
